---
title: "AutoFocus"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(magrittr)
library(plotly)
library(dendextend)
library(igraph)
library(DT)

source(codes.makepath("autofocus/Frontend_Modules.R"))
load("~/Documents/Documents - MAC203001/JanLab/QD_R.rda")
R <- QD_results_lm
dend_data <- ggdendro::dendro_data(as.dendrogram(R$HCL), type = "rectangle")
dend_xy <- R$HCL %>% as.dendrogram %>%get_nodes_xy()
order_coords <- data.frame(index = R$order, 
                             x = round(dend_xy[,1], digits = 10), 
                             y = round(dend_xy[,2], digits = 10)) 
  
order_coords <- order_coords[order(order_coords$index),]
  
dend<-plot_dend_fast(R, order_coords, dend_data) 

selected_node = reactiveValues(n = NA,last=NA)
observeEvent(event_data("plotly_click"),{
  d<-event_data("plotly_click")
  if (!is.null(d$y)){
    if (d$y > 0 & length(order_coords$index[which(order_coords$y ==d$y)])==1){
      selected_node$last = selected_node$n
      selected_node$n = order_coords$index[which(order_coords$y ==d$y)]
      
  }}})

    y_axis <- list(
      title = "",
      showline = TRUE,
      showticklabels = F,
      mirror="ticks",
      showgrid = F,
      zeroline = F,
      linecolor = toRGB("black"),
      linewidth = 2
    )
    x_axis <- list(
      title = "",
      showline = TRUE,
      showticklabels = F,
      mirror="ticks",
      showgrid = F,
      zeroline = F,
      linecolor = toRGB("black"),
      linewidth = 2
    )
```


Row 
-----------------------------------------------------------------------


### Dendrogram View 

```{r}
renderPlotly({
 
    ### Dendrogram ###
    view_range <- match(R$clusts[as.double(selected_node$n)][[1]], R$HCL$order)
    x <- c((min(view_range)-1),(max(view_range)+1))
    y <- c(-0.1, (order_coords[selected_node$n,3])+0.1)

    x_axis$range <- x
    y_axis$range <- y
    if (!is.na(selected_node$last)){
      dend<-
        add_markers(dend,
                          x=order_coords[selected_node$last,2],
                          y=order_coords[selected_node$last,3],
                          marker = list(color = R$colors[selected_node$last], size = 9))
      }
    dend<-add_markers(dend,
                  x=order_coords[selected_node$n,2],
                  y=order_coords[selected_node$n,3],
                  marker = list(color = "yellow", size = 9)) %>% 

    layout(
      xaxis = x_axis,
      yaxis = y_axis,
      showlegend = F
    )
  })
```

Row 
-----------------------------------------------------------------------

### Module List View

```{r}
DT::renderDataTable(
    datatable(data.frame(R$annos[R$clusts[[selected_node$n]],])), fillContainer = TRUE)
```

Row 
-----------------------------------------------------------------------

### Network View
```{r}
renderPlotly({
      
    axis <- list(
      title = "",
      showline = TRUE,
      showticklabels = F,
      mirror="ticks",
      showgrid = F,
      zeroline = F,
      linecolor = toRGB("black"),
      linewidth = 2
    )
    
    if (is.na(selected_node$n)){
      net = plotly_empty() %>% add_annotations(text = "Select a Cluster to View", showarrow = F) %>% layout(xaxis = axis, yaxis = axis)
    }
    else{
        net<-plotly::layout(
        cluster_net(R, as.double(selected_node$n)),
        xaxis = axis,
        yaxis = axis,
        showlegend=F
      )
    }

  net
})
```

### Node Annotations

```{r}
renderPlotly({
    axis <- list(
      
      showline = TRUE,
      showticklabels = F,
      mirror="ticks",
      showgrid = F,
      zeroline = F,
      linecolor = toRGB("black"),
      linewidth = 2
    )
    if (is.na(selected_node$n)){
      sunburst = plotly_empty() %>% 
        add_annotations(text = "Select a Cluster for Annotation Details", showarrow = F) %>% 
        layout(xaxis = axis, yaxis = axis)

    }

    else{
      barplot_df <- get_anno_data(R, selected_node$n)
      sunburst <- plot_ly(barplot_df, labels = ~labels, parents = ~parents, values = ~values,type = 'sunburst', branchvalues = 'remainder')
    }
    
    sunburst %>% layout(
      title="Module Node Annotations")
    sunburst
    }
  )
```


Row 
-----------------------------------------------------------------------
### Node List

```{r}
DT::renderDataTable(
    datatable(data.frame(R$annos[R$clusts[[selected_node$n]],])), options = list(scrollX = '400px', scrollY='360px'), fillContainer = TRUE)
```

